### ISSUE TITLE
How to start

### ISSUE THREAD

**Issue by YunaBraska** [springboot-testcontainer/springboot-testcontainer-rabbitmq#18]
Hi,

I would love to test my app using rabbitmq with this library. But its not really descriptive and there is no example around.
Shouldn't be this `spring.rabbitmq.addresses` default? I don't know where the container is starting. Its pretty frustrating cause I get the container as it seems but can't connect for some reasons.

```
Failed to bind properties under 'spring.rabbitmq' to org.springframework.boot.autoconfigure.amqp.RabbitProperties:

    Property: spring.rabbitmq.addresses
    Value: ${embedded.container.rabbitmq.host}:${embedded.container.rabbitmq.port}
    Origin: class path resource [application.yml]:23:16
    Reason: For input string: "${embedded.container.rabbitmq.port}"

```

Or ei get this without any property which I expect should work on default:
```
[main        ] ERROR .c.AbstractBuildingEmbeddedContainer - Failed to start rabbitmq-container
com.avides.springboot.springtainer.common.container.ContainerStartupFailedException: Timeout waiting for result with exception
	at com.avides.springboot.springtainer.common.container.AbstractBuildingEmbeddedContainer.waitUntilReady(AbstractBuildingEmbeddedContainer.java:198)
	at com.avides.springboot.springtainer.common.container.AbstractBuildingEmbeddedContainer.<init>(AbstractBuildingEmbeddedContainer.java:51)
	at com.avides.springboot.springtainer.rabbitmq.EmbeddedRabbitmqContainerAutoConfiguration$RabbitmqContainer.<init>(EmbeddedRabbitmqContainerAutoConfiguration.java:43)
	at com.avides.springboot.springtainer.rabbitmq.EmbeddedRabbitmqContainerAutoConfiguration.rabbitmqContainer(EmbeddedRabbitmqContainerAutoConfiguration.java:36)
	at com.avides.springboot.springtainer.rabbitmq.EmbeddedRabbitmqContainerAutoConfiguration$$EnhancerBySpringCGLIB$$5882ed2b.CGLIB$rabbitmqContainer$0(<generated>)
	at com.avides.springboot.springtainer.rabbitmq.EmbeddedRabbitmqContainerAutoConfiguration$$EnhancerBySpringCGLIB$$5882ed2b$$FastClassBySpringCGLIB$$a888cd3d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at com.avides.springboot.springtainer.rabbitmq.EmbeddedRabbitmqContainerAutoConfiguration$$EnhancerBySpringCGLIB$$5882ed2b.rabbitmqContainer(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
Caused by: com.rabbitmq.client.ShutdownSignalException: connection error
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:494)
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:315)
	... 15 common frames omitted
Caused by: java.io.EOFException: null
	at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:295)
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:91)
	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:164)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:596)
```

Also the line `return Collections.singletonList("/var/lib/rabbitmq");` could lead to a problem using Windows or is this the internal docker resource?

The image should be also configurable
```
setDockerImage("rabbitmq:3.8.1-alpine");
```

I am using Mac OS and Spring boot 2.0.9

**Comment by fegbers** [comment]
Hi,
thanks for your questions and your feedback.

> I would love to test my app using rabbitmq with this library. But its not really descriptive and there is no example around.

Yeah, you are right.. But we are planning to write an example project or provide some repository links to show the configuration.
But at all it is enough to add the dependency and to override the spring properties for the rabbitmq address like this example: `spring.rabbitmq.addresses=${embedded.container.rabbitmq.host}:${embedded.container.rabbitmq.port}
`

> Or ei get this without any property which I expect should work on default:

We already had some problems with timeouts on Mac OS. The container have a start up timeout of 30 seconds and sometimes the container needs some more time. To avoid this problem, it is possible to override the default (embedded.container.rabbitmq.startup-timeout). If the problem still exist, please provide some more informations or perhaps a link for your test project.

> Also the line return Collections.singletonList("/var/lib/rabbitmq"); could lead to a problem using Windows or is this the internal docker resource?

This is a feature that [docker](https://docs.docker.com/storage/tmpfs/) provides. Therefore it is also handled by Docker. As far as we know, we have no problems on Windows.

> The image should be also configurable

As described in the README, it is possible to overwrite the configured standard setting.

I hope i could help you.
Greetings

**Comment by YunaBraska** [comment]
@fegbers thx the timeout helped and worked. At least it was starting. I didn't do something with it yet cause the start time is pretty slow for running tests against it. 

````
16:04:58.892 [main        ] INFO  .c.AbstractBuildingEmbeddedContainer - Checking rabbitmq-container... (Timeout: 180000s)
16:06:38.270 [main        ] INFO  .c.AbstractBuildingEmbeddedContainer - rabbitmq-container started (Duration: 99377ms, Host: localhost)

````

**Comment by fegbers** [comment]
> @fegbers thx the timeout helped and worked. At least it was starting. I didn't do something with it yet cause the start time is pretty slow for running tests against it.
> 
> ```
> 16:04:58.892 [main        ] INFO  .c.AbstractBuildingEmbeddedContainer - Checking rabbitmq-container... (Timeout: 180000s)
> 16:06:38.270 [main        ] INFO  .c.AbstractBuildingEmbeddedContainer - rabbitmq-container started (Duration: 99377ms, Host: localhost)
> ```

I am glad to hear that I could help you @YunaBraska ! Of course the start time is a bit slow. But unfortunately I can't tell you why. We also tested this version on a Mac. On a "normally" configured Mac without an extremely high workload, we had a start time of ~ 15 seconds.
On a Linux machine, i have a start time of ~ 8 seconds.

**Comment by YunaBraska** [comment]
@fegbers so you think there is no way to configure rabbitMq to start with the smallest support of feature like without UI? I don't know rabbit so much... I could go for the 8-15 seconds but currently is not usable for me :( I would so love to support you and use you library but its not working for me within two minutes waiting time. I Think we can close this issue here as the original question is answered but setting the timeout higher

**Comment by fegbers** [comment]
> @fegbers so you think there is no way to configure rabbitMq to start with the smallest support of feature like without UI? I don't know rabbit so much... I could go for the 8-15 seconds but currently is not usable for me :( I would so love to support you and use you library but its not working for me within two minutes waiting time. I Think we can close this issue here as the original question is answered but setting the timeout higher

The image is already the smallest one (without UI).
As already mentioned, we don't have that kind of starting time issues.. Perhaps you don't have enough resources on your mac? 
Okay, i will close the issue.
Feel free to reopen the issue or create a new one for further problems.
Hopefully you can solve your performance issues.
Greetings
